@ShiftManagementApp.API_HostAddress = http://localhost:5260

### Get All Persons
GET {{ShiftManagementApp.API_HostAddress}}/persons
Accept: application/json

### Create a New Person
POST {{ShiftManagementApp.API_HostAddress}}/persons
Content-Type: application/json
Accept: application/json

{
    "idCard": 1233188475,    
    "FirstName": "Juan",
    "LastName": "Figueroa",
    "Email": "juan.Figueroa@example.com",
    "PhoneNumber": "3219748471",
    "PersonType": 1
}

### Get a New Person

GET {{ShiftManagementApp.API_HostAddress}}/persons/5


### Edit a Person
PUT {{ShiftManagementApp.API_HostAddress}}/persons/5
Content-Type: application/json
Accept: application/json

{
    "id": 5,
    "idCard": 30732024,
    "firstName": "TestPrueba",
    "lastName": "Test",
    "email": "Test@gmail.com",
    "phoneNumber": "2131231",
    "personType": 1
}

### Delete a Person

DELETE {{ShiftManagementApp.API_HostAddress}}/persons/1
